# Generated by Django 2.1 on 2018-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20181002_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='published',
            field=models.DateField(db_index=True),
        ),
    ]
