# Generated by Django 2.1 on 2018-08-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='url',
            new_name='link',
        ),
    ]
