# Generated by Django 2.1 on 2018-09-20 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180829_0237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(db_index=True)),
                ('link', models.URLField()),
                ('html', models.TextField()),
                ('feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='feeds.Feed')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('feed', 'title', 'published')},
        ),
    ]
