# Generated by Django 2.1 on 2018-09-25 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('feeds', '0003_auto_20180920_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='companies',
            field=models.ManyToManyField(related_name='articles', to='analysis.Company'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='analysis.Section'),
        ),
        migrations.AddField(
            model_name='article',
            name='segments',
            field=models.ManyToManyField(related_name='articles', to='analysis.Segment'),
        ),
        migrations.AddField(
            model_name='feed',
            name='companies',
            field=models.ManyToManyField(related_name='feeds', to='analysis.Company'),
        ),
    ]
