# Generated by Django 2.1 on 2018-10-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_auto_20181002_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
