# Generated by Django 2.1 on 2018-10-02 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        ('feeds', '0007_article_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsletter.Newsletter'),
        ),
    ]
