# Generated by Django 2.1 on 2018-10-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_article_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='newsletter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='newsletter.Newsletter'),
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='analysis.Section'),
        ),
    ]
