# Generated by Django 2.1 on 2018-10-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_auto_20181002_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='articles', to='analysis.Segment'),
        ),
    ]
