# Generated by Django 2.1.3 on 2018-11-30 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20180925_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='analysis.Segment'),
        ),
    ]
